---
- hosts: nfs
  become: true
  roles:
    - nfs

- hosts: all
  become: true
  roles:
    - ntp
    - nfs_client

- hosts: master
  become: true
  roles:
    - k8s

- hosts: node
  become: true
  roles:
    - k8s_node

- hosts: master
  become: false
  roles:
    - despliegue
